__version__ = "1.0.2"
__author__ = "Yaozhong Zhang, Gaofei Jiang"
__maintainer__ = "Yaozhong Zhang, Gaofei Jiang"
__email__ = "Yaozhongzyz@163.com"
__institution__ = "Nanjing Agricultural University"
__status__ = "Development"