__version__ = "1.1.2"
__author__ = "Yaozhong Zhang, Gaofei Jiang"
__maintainer__ = "Yaozhong Zhang, Gaofei Jiang"
__email__ = "Yaozhongzyz@163.com, gjiang@njau.edu.cn"
__institution__ = "Nanjing Agricultural University"
__status__ = "Development"